---
version: 2
plan:
  project-key: DEV
  key: PERDEV
  name: Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'true'
  - script:
      interpreter: SHELL
      scripts:
      - echo "ss"
      conditions:
      - variable:
          equals:
            test_stage_build: 'true'
  - script:
      interpreter: SHELL
      scripts:
      - |-

        ### using cen ###
        echo "dasda"
      conditions:
      - variable:
          equals:
            planRepository.1.branchName: develop
  - script:
      interpreter: SHELL
      scripts:
       - |-
         touch sadf.txt
         rm sadf.txt
         touch jj.txt
          
  requirements:
   - system.docker.executable
  artifacts:
    - name: Helm environment files
      location: './'
      pattern: '*.txt'
      shared: true
      required: true

variables:
  test: 'falsafe'
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 1
    after-inactive-days: 7
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default