---
version: 2
#server-name: DevStack Bamboo#
plan:
  project-key: TEST
  key: FIT
  name: first
stages:
  - Default Stage:
#      manual: false
#      final: false
#      jobs:
        - building
#Default Job:
building:
#  key: JOB1
  tasks:
    - script:
       scripts:
        - echo "test"
        - echo PASS=${bamboo.pass} > VERSION.properties
    - inject-variables:
##       task-description: task1
       file: VERSION.properties
       scope: RESULT
       namespace: inject
    - script:
       interpreter: SHELL
       scripts:
         - docker login -u deaamoflih -p ${bamboo.inject.PASS}
    - script: echo "task3" > deployment.yaml
    - maven:
       executable: Maven 3.6.3
       jdk: JDK 11.0.2
       goal: clean package -DskipTests=true
       Environment variables: SS_SERNAME=ss
    - script: 
       scripts:
        - docker build -t deaamoflih/sample:2.0 .
    - script: 
       scripts:
        - docker push deaamoflih/sample:2.0     
  artifacts:
    - name: Openshift deployment descriptor
      location: ./
      pattern: deployment.yaml
      shared: true
      required: true        
  requirements:
    - system.docker.executable
    - system.builder.mvn3.Maven 3
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: never
  link-to-jira: true
labels: []
other:
  concurrent-build-plugin: system-default

