---
version: 2
#server-name: DevStack Bamboo#
plan:
  project-key: TEST
  key: FIT
  name: first
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
    - script:
       scripts:
        - echo "test"
        - echo PASS=${bamboo.pass} > VERSION.properties
    - inject-variables:
       task-description: task1
       file: VERSION.properties
       scope: RESULT
       namespace: inject
    - script:
       interpreter: SHELL
       scripts:
         - docker login -u deaamoflih -p ${bamboo.inject.PASS}
    - script: echo "task3" > deployment.yaml
    - script: 
       scripts:
        - docker build -t deaamoflih/sample:2.0 .
    - script: 
       scripts:
        - docker push deaamoflih/sample:2.0     
  artifacts:
    - name: Openshift deployment descriptor
      location: ./
      pattern: deployment.yaml
      shared: true
      required: true        
  requirements:
    - system.docker.executable
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: never
  link-to-jira: true
labels: []
other:
  concurrent-build-plugin: system-default

